### ISSUE TITLE
analyse the class without main method

### ISSUE THREAD

**Issue by Roy-NJU** [parasol-aser/tsa#1]
Hi:
    I can't use the TSA tool to analyse the class without main method, how can I do it? The following is the err snapshot:
C:\tsa-master>java -jar tsa.jar Shared
****************************************************
* Loading and configuring SOOT for instrumentation *
****************************************************
Exception in thread "main" java.lang.RuntimeException: Main-class has no main method!
        at soot.Scene.setMainClass(Scene.java:155)
        at edu.tamu.cse.aser.tsa.Main.main(Main.java:68)

Thanks!

**Comment by parasol-aser** [comment]
hi, customized entry method is now supported. You can specify the name of entry method in `tsa.conf`, for example, `tsa.entry=test`. Then the method `test` will be used as the entry method (if you don't have a main method).
